CREATE TABLE ROL (
    ID_ROL INT PRIMARY KEY,
    Nombre VARCHAR(100),
    Descripcion VARCHAR(255)
);

CREATE TABLE PERMIS (
    ID_PERMIS INT PRIMARY KEY,
    Nom VARCHAR(100),
    Descripcion VARCHAR(255)
);

CREATE TABLE ROL_PERMIS (
    ID_ROL INT,
    ID_PERMIS INT,
    PRIMARY KEY (ID_ROL, ID_PERMIS),
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    FOREIGN KEY (ID_PERMIS) REFERENCES PERMIS(ID_PERMIS)
);

CREATE TABLE USUARI (
    ID_USER INT PRIMARY KEY,
    Nombre VARCHAR(100),
    ID_ROL INT,
    ID_TARGETA VARCHAR(255),
    FOREIGN KEY (ID_TARGETA) REFERENCES TARGETA(ID_TARGETA)
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

CREATE TABLE DISPOSITIU (
    ID_DISPOSITIU INT PRIMARY KEY,
    Nom VARCHAR(100),
    Ubicacio VARCHAR(255),
    Actiu BOOLEAN,
);

CREATE TABLE TARGETA (
    ID_TARGETA INT PRIMARY KEY,
    CODI VARCHAR(100),
    Estat BOOLEAN,
);

CREATE TABLE CURS (
    ID_CURS INT PRIMARY KEY,
    NOM VARCHAR(100),
    ANY_INICI DATE,
    ANY_FI DATE,
    ACTIU BOOLEAN
);

CREATE TABLE GRUP (
    ID_GRUP INT PRIMARY KEY,
    NOM VARCHAR(100),
    ID_CURS INT,
    TUTOR_ID_USUARI INT,
    FOREIGN KEY (ID_CURS) REFERENCES CURS(ID_CURS),
    FOREIGN KEY (TUTOR_ID_USUARI) REFERENCES USUARI(ID_USER)
);

CREATE TABLE USUARI_GRUP (
    ID_USUARI INT,
    ID_GRUP INT,
    ROL_GRUP ENUM('ALUMNE','PROFESSOR','TUTOR'),
    PRIMARY KEY (ID_USUARI, ID_GRUP),
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI(ID_USER),
    FOREIGN KEY (ID_GRUP) REFERENCES GRUP(ID_GRUP)
);

CREATE TABLE AULA (
    ID_AULA INT PRIMARY KEY,
    NOM VARCHAR(100),
    UBICACIO VARCHAR(255),
    CAPACITAT INT,
    ACTIU BOOLEAN
);

CREATE TABLE HORARI (
    ID_HORARI INT PRIMARY KEY,
    ID_GRUP INT,
    ID_PROFE INT,
    ID_AULA INT,
    DIA_SETMANA ENUM('DILLUNS','DIMARTS','DIMECRES','DIJOUS','DIVENDRES'),
    HORA_INICI TIME,
    HORA_FI TIME,
    FOREIGN KEY (ID_GRUP) REFERENCES GRUP(ID_GRUP),
    FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA),
    FOREIGN KEY (ID_PROFE) REFERENCES USUARI(ID_USER)
);

CREATE TABLE ASISTENCIA (
    ID_ASISTENCIA INT PRIMARY KEY,
    ID_TARGETA INT,
    ID_DISPOSITIU INT,
    ID_HORARI INT,
    Fecha DATETIME,
    Estat ENUM('Present','Absent','Justificat'),
    FOREIGN KEY (ID_TARGETA) REFERENCES TARGETA(ID_TARGETA),
    FOREIGN KEY (ID_DISPOSITIU) REFERENCES DISPOSITIU(ID_DISPOSITIU),
    FOREIGN KEY (ID_HORARI) REFERENCES HORARI(ID_HORARI)
);

CREATE TABLE JUSTIFICACIO (
    ID_JUSTIFICACIO INT PRIMARY KEY,
    ID_ASISTENCIA INT,
    ID_USER INT,
    Tipus VARCHAR(100),
    FOREIGN KEY (ID_ASISTENCIA) REFERENCES ASISTENCIA(ID_ASISTENCIA),
    FOREIGN KEY (ID_USER) REFERENCES USUARI(ID_USER)
);

CREATE TABLE RETARD (
    ID_RETARD INT PRIMARY KEY,
    ID_ASISTENCIA INT,
    MINUTS_TARD INT,
    JUSTIFICANT BOOLEAN,
    FOREIGN KEY (ID_ASISTENCIA) REFERENCES ASISTENCIA(ID_ASISTENCIA)
);
