DROP TABLE IF EXISTS RETARD;
DROP TABLE IF EXISTS JUSTIFICACIO;
DROP TABLE IF EXISTS ASISTENCIA;
DROP TABLE IF EXISTS HORARI;
DROP TABLE IF EXISTS USUARI_GRUP;
DROP TABLE IF EXISTS GRUP;
DROP TABLE IF EXISTS USUARI;
DROP TABLE IF EXISTS TARGETA;
DROP TABLE IF EXISTS DISPOSITIU;
DROP TABLE IF EXISTS AULA;
DROP TABLE IF EXISTS CURS;
DROP TABLE IF EXISTS ROL_PERMIS;
DROP TABLE IF EXISTS PERMIS;
DROP TABLE IF EXISTS ROL;


CREATE TABLE ROL (
    ID_ROL INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100),
    Descripcion VARCHAR(255)
);

CREATE TABLE PERMIS (
    ID_PERMIS INT PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(100),
    Descripcion VARCHAR(255)
);

CREATE TABLE TARGETA (
    ID_TARGETA INT PRIMARY KEY AUTO_INCREMENT,
    CODI VARCHAR(100),
    Estat BOOLEAN
);

CREATE TABLE CURS (
    ID_CURS INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100),
    ANY_INICI DATE,
    ANY_FI DATE,
    ACTIU BOOLEAN
);

CREATE TABLE AULA (
    ID_AULA INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100),
    UBICACIO VARCHAR(255),
    CAPACITAT INT,
    ACTIU BOOLEAN
);

CREATE TABLE DISPOSITIU (
    ID_DISPOSITIU INT PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(100),
    Ubicacio VARCHAR(255),
    Actiu BOOLEAN
);

CREATE TABLE USUARI (
    ID_USER INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(100),
    ID_ROL INT,
    ID_TARGETA INT,
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    FOREIGN KEY (ID_TARGETA) REFERENCES TARGETA(ID_TARGETA)
);

CREATE TABLE ROL_PERMIS (
    ID_ROL INT NOT NULL,
    ID_PERMIS INT NOT NULL,
    PRIMARY KEY (ID_ROL, ID_PERMIS),
    FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL),
    FOREIGN KEY (ID_PERMIS) REFERENCES PERMIS(ID_PERMIS)
);

CREATE TABLE GRUP (
    ID_GRUP INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(100),
    ID_CURS INT,
    TUTOR_ID_USUARI INT,
    FOREIGN KEY (ID_CURS) REFERENCES CURS(ID_CURS),
    FOREIGN KEY (TUTOR_ID_USUARI) REFERENCES USUARI(ID_USER)
);

CREATE TABLE USUARI_GRUP (
    ID_USUARI INT,
    ID_GRUP INT,
    ROL_GRUP ENUM('ALUMNE','PROFESSOR','PERSONAL'),
    PRIMARY KEY (ID_USUARI, ID_GRUP),
    FOREIGN KEY (ID_USUARI) REFERENCES USUARI(ID_USER),
    FOREIGN KEY (ID_GRUP) REFERENCES GRUP(ID_GRUP)
);

CREATE TABLE HORARI (
    ID_HORARI INT PRIMARY KEY AUTO_INCREMENT,
    ID_GRUP INT,
    ID_AULA INT,
    DIA_SETMANA ENUM('DILLUNS','DIMARTS','DIMECRES','DIJOUS','DIVENDRES'),
    HORA_INICI TIME,
    HORA_FI TIME,
    FOREIGN KEY (ID_GRUP) REFERENCES GRUP(ID_GRUP),
    FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA)
);

CREATE TABLE ASISTENCIA (
    ID_ASISTENCIA INT PRIMARY KEY AUTO_INCREMENT,
    ID_TARGETA INT,
    ID_DISPOSITIU INT,
    ID_HORARI INT,
    Fecha TIMESTAMP,
    Estat ENUM('PRESENT','ABSENT','JUSTIFICAT'),
    FOREIGN KEY (ID_TARGETA) REFERENCES TARGETA(ID_TARGETA),
    FOREIGN KEY (ID_DISPOSITIU) REFERENCES DISPOSITIU(ID_DISPOSITIU),
    FOREIGN KEY (ID_HORARI) REFERENCES HORARI(ID_HORARI)
);

CREATE TABLE JUSTIFICACIO (
    ID_JUSTIFICACIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_ASISTENCIA INT,
    ID_USER INT,
    Tipus VARCHAR(100),
    FOREIGN KEY (ID_ASISTENCIA) REFERENCES ASISTENCIA(ID_ASISTENCIA),
    FOREIGN KEY (ID_USER) REFERENCES USUARI(ID_USER)
);

CREATE TABLE RETARD (
    ID_RETARD INT PRIMARY KEY AUTO_INCREMENT,
    ID_ASISTENCIA INT,
    MINUTS_TARD INT,
    JUSTIFICANT BOOLEAN,
    FOREIGN KEY (ID_ASISTENCIA) REFERENCES ASISTENCIA(ID_ASISTENCIA)
);
